/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTaskLoopRuns implements TaskLoopRunInterface
type FakeTaskLoopRuns struct {
	Fake *FakeTektonV1beta1
	ns   string
}

var tasklooprunsResource = schema.GroupVersionResource{Group: "tekton.dev", Version: "v1beta1", Resource: "taskloopruns"}

var tasklooprunsKind = schema.GroupVersionKind{Group: "tekton.dev", Version: "v1beta1", Kind: "TaskLoopRun"}

// Get takes name of the taskLoopRun, and returns the corresponding taskLoopRun object, and an error if there is any.
func (c *FakeTaskLoopRuns) Get(name string, options v1.GetOptions) (result *v1beta1.TaskLoopRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tasklooprunsResource, c.ns, name), &v1beta1.TaskLoopRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TaskLoopRun), err
}

// List takes label and field selectors, and returns the list of TaskLoopRuns that match those selectors.
func (c *FakeTaskLoopRuns) List(opts v1.ListOptions) (result *v1beta1.TaskLoopRunList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tasklooprunsResource, tasklooprunsKind, c.ns, opts), &v1beta1.TaskLoopRunList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.TaskLoopRunList{ListMeta: obj.(*v1beta1.TaskLoopRunList).ListMeta}
	for _, item := range obj.(*v1beta1.TaskLoopRunList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested taskLoopRuns.
func (c *FakeTaskLoopRuns) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tasklooprunsResource, c.ns, opts))

}

// Create takes the representation of a taskLoopRun and creates it.  Returns the server's representation of the taskLoopRun, and an error, if there is any.
func (c *FakeTaskLoopRuns) Create(taskLoopRun *v1beta1.TaskLoopRun) (result *v1beta1.TaskLoopRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tasklooprunsResource, c.ns, taskLoopRun), &v1beta1.TaskLoopRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TaskLoopRun), err
}

// Update takes the representation of a taskLoopRun and updates it. Returns the server's representation of the taskLoopRun, and an error, if there is any.
func (c *FakeTaskLoopRuns) Update(taskLoopRun *v1beta1.TaskLoopRun) (result *v1beta1.TaskLoopRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tasklooprunsResource, c.ns, taskLoopRun), &v1beta1.TaskLoopRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TaskLoopRun), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTaskLoopRuns) UpdateStatus(taskLoopRun *v1beta1.TaskLoopRun) (*v1beta1.TaskLoopRun, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tasklooprunsResource, "status", c.ns, taskLoopRun), &v1beta1.TaskLoopRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TaskLoopRun), err
}

// Delete takes name of the taskLoopRun and deletes it. Returns an error if one occurs.
func (c *FakeTaskLoopRuns) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tasklooprunsResource, c.ns, name), &v1beta1.TaskLoopRun{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTaskLoopRuns) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tasklooprunsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.TaskLoopRunList{})
	return err
}

// Patch applies the patch and returns the patched taskLoopRun.
func (c *FakeTaskLoopRuns) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.TaskLoopRun, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tasklooprunsResource, c.ns, name, pt, data, subresources...), &v1beta1.TaskLoopRun{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.TaskLoopRun), err
}
